name: dependency_manager
description: Package desenvolvido para prover funções para o controle e gerenciamento de instâncias de dependências em app.
version: 1.0.5
homepage: https://github.com/Suebersson/dependency_manager.git
repository: https://github.com/Suebersson/dependency_manager

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  dart_dev_utils: ^1.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
